INSERT INTO public.users (user_id, country, region) VALUES (1, 'USA', 'California');
INSERT INTO public.users (user_id, country, region) VALUES (2, 'USA', 'Texas');
INSERT INTO public.users (user_id, country, region) VALUES (3, 'USA', 'New York');
INSERT INTO public.users (user_id, country, region) VALUES (4, 'Canada', 'Ontario');
INSERT INTO public.users (user_id, country, region) VALUES (5, 'Canada', 'Quebec');
INSERT INTO public.users (user_id, country, region) VALUES (6, 'Canada', 'British Columbia');
INSERT INTO public.users (user_id, country, region) VALUES (7, 'UK', 'England');
INSERT INTO public.users (user_id, country, region) VALUES (8, 'UK', 'Scotland');
INSERT INTO public.users (user_id, country, region) VALUES (9, 'UK', 'Wales');
INSERT INTO public.users (user_id, country, region) VALUES (10, 'Germany', 'Bavaria');
INSERT INTO public.users (user_id, country, region) VALUES (11, 'Germany', 'Berlin');
INSERT INTO public.users (user_id, country, region) VALUES (12, 'Germany', 'Hesse');
INSERT INTO public.users (user_id, country, region) VALUES (13, 'France', 'Île-de-France');
INSERT INTO public.users (user_id, country, region) VALUES (14, 'France', 'Provence-Alpes-Côte');
INSERT INTO public.users (user_id, country, region) VALUES (15, 'France', 'Nouvelle-Aquitaine');
INSERT INTO public.users (user_id, country, region) VALUES (16, 'India', 'Maharashtra');
INSERT INTO public.users (user_id, country, region) VALUES (17, 'India', 'Karnataka');
INSERT INTO public.users (user_id, country, region) VALUES (18, 'India', 'Tamil Nadu');
INSERT INTO public.users (user_id, country, region) VALUES (19, 'Australia', 'New South Wales');
INSERT INTO public.users (user_id, country, region) VALUES (20, 'Australia', 'Victoria');
INSERT INTO public.users (user_id, country, region) VALUES (21, 'Australia', 'Queensland');
INSERT INTO public.users (user_id, country, region) VALUES (22, 'Brazil', 'São Paulo');
INSERT INTO public.users (user_id, country, region) VALUES (23, 'Brazil', 'Rio de Janeiro');
INSERT INTO public.users (user_id, country, region) VALUES (24, 'Brazil', 'Bahia');
INSERT INTO public.users (user_id, country, region) VALUES (25, 'Japan', 'Tokyo');
INSERT INTO public.users (user_id, country, region) VALUES (26, 'Japan', 'Osaka');
INSERT INTO public.users (user_id, country, region) VALUES (27, 'Japan', 'Hokkaido');
INSERT INTO public.users (user_id, country, region) VALUES (28, 'Mexico', 'Mexico City');
INSERT INTO public.users (user_id, country, region) VALUES (29, 'Mexico', 'Jalisco');
INSERT INTO public.users (user_id, country, region) VALUES (30, 'Mexico', 'Nuevo León');
INSERT INTO public.users (user_id, country, region) VALUES (31, 'South Africa', 'Gauteng');
INSERT INTO public.users (user_id, country, region) VALUES (32, 'South Africa', 'Western Cape');
INSERT INTO public.users (user_id, country, region) VALUES (33, 'South Africa', 'KwaZulu-Natal');
INSERT INTO public.users (user_id, country, region) VALUES (34, 'Russia', 'Moscow');
INSERT INTO public.users (user_id, country, region) VALUES (35, 'Russia', 'Saint Petersburg');
INSERT INTO public.users (user_id, country, region) VALUES (36, 'Russia', 'Novosibirsk');
INSERT INTO public.users (user_id, country, region) VALUES (37, 'Italy', 'Lombardy');
INSERT INTO public.users (user_id, country, region) VALUES (38, 'Italy', 'Lazio');
INSERT INTO public.users (user_id, country, region) VALUES (39, 'Italy', 'Sicily');
INSERT INTO public.users (user_id, country, region) VALUES (40, 'Spain', 'Catalonia');
INSERT INTO public.users (user_id, country, region) VALUES (41, 'Spain', 'Madrid');
INSERT INTO public.users (user_id, country, region) VALUES (42, 'Spain', 'Andalusia');
INSERT INTO public.users (user_id, country, region) VALUES (43, 'China', 'Beijing');
INSERT INTO public.users (user_id, country, region) VALUES (44, 'China', 'Shanghai');
INSERT INTO public.users (user_id, country, region) VALUES (45, 'China', 'Guangdong');
INSERT INTO public.users (user_id, country, region) VALUES (46, 'Netherlands', 'North Holland');
INSERT INTO public.users (user_id, country, region) VALUES (47, 'Netherlands', 'South Holland');
INSERT INTO public.users (user_id, country, region) VALUES (48, 'Netherlands', 'Utrecht');
INSERT INTO public.users (user_id, country, region) VALUES (49, 'Sweden', 'Stockholm');
INSERT INTO public.users (user_id, country, region) VALUES (50, 'Sweden', 'Västra Götaland');
INSERT INTO public.users (user_id, country, region) VALUES (51, 'USA', 'Florida');
INSERT INTO public.users (user_id, country, region) VALUES (52, 'USA', 'Illinois');
INSERT INTO public.users (user_id, country, region) VALUES (53, 'Canada', 'Alberta');
INSERT INTO public.users (user_id, country, region) VALUES (54, 'Canada', 'Nova Scotia');
INSERT INTO public.users (user_id, country, region) VALUES (55, 'UK', 'Northern Ireland');
INSERT INTO public.users (user_id, country, region) VALUES (56, 'Germany', 'Saxony');
INSERT INTO public.users (user_id, country, region) VALUES (57, 'France', 'Brittany');
INSERT INTO public.users (user_id, country, region) VALUES (58, 'India', 'Gujarat');
INSERT INTO public.users (user_id, country, region) VALUES (59, 'India', 'Punjab');
INSERT INTO public.users (user_id, country, region) VALUES (60, 'Australia', 'South Australia');
INSERT INTO public.users (user_id, country, region) VALUES (61, 'Brazil', 'Paraná');
INSERT INTO public.users (user_id, country, region) VALUES (62, 'Brazil', 'Minas Gerais');
INSERT INTO public.users (user_id, country, region) VALUES (63, 'Japan', 'Kyoto');
INSERT INTO public.users (user_id, country, region) VALUES (64, 'Mexico', 'Chiapas');
INSERT INTO public.users (user_id, country, region) VALUES (65, 'South Africa', 'Eastern Cape');
INSERT INTO public.users (user_id, country, region) VALUES (66, 'Russia', 'Tatarstan');
INSERT INTO public.users (user_id, country, region) VALUES (67, 'Italy', 'Veneto');
INSERT INTO public.users (user_id, country, region) VALUES (68, 'Spain', 'Valencia');
INSERT INTO public.users (user_id, country, region) VALUES (69, 'China', 'Sichuan');
INSERT INTO public.users (user_id, country, region) VALUES (70, 'Netherlands', 'Gelderland');
INSERT INTO public.users (user_id, country, region) VALUES (71, 'Sweden', 'Skåne');
INSERT INTO public.users (user_id, country, region) VALUES (72, 'USA', 'Michigan');
INSERT INTO public.users (user_id, country, region) VALUES (73, 'USA', 'Ohio');
INSERT INTO public.users (user_id, country, region) VALUES (74, 'Canada', 'Manitoba');
INSERT INTO public.users (user_id, country, region) VALUES (75, 'UK', 'Yorkshire');
INSERT INTO public.users (user_id, country, region) VALUES (76, 'Germany', 'Hamburg');
INSERT INTO public.users (user_id, country, region) VALUES (77, 'France', 'Normandy');
INSERT INTO public.users (user_id, country, region) VALUES (78, 'India', 'Rajasthan');
INSERT INTO public.users (user_id, country, region) VALUES (79, 'Australia', 'Tasmania');
INSERT INTO public.users (user_id, country, region) VALUES (80, 'Brazil', 'Ceará');
INSERT INTO public.users (user_id, country, region) VALUES (81, 'Japan', 'Hiroshima');
INSERT INTO public.users (user_id, country, region) VALUES (82, 'Mexico', 'Nuevo León');
INSERT INTO public.users (user_id, country, region) VALUES (83, 'South Africa', 'Limpopo');
INSERT INTO public.users (user_id, country, region) VALUES (84, 'Russia', 'Krasnodar');
INSERT INTO public.users (user_id, country, region) VALUES (85, 'Italy', 'Piedmont');
INSERT INTO public.users (user_id, country, region) VALUES (86, 'Spain', 'Galicia');
INSERT INTO public.users (user_id, country, region) VALUES (87, 'China', 'Shandong');
INSERT INTO public.users (user_id, country, region) VALUES (88, 'Netherlands', 'Friesland');
INSERT INTO public.users (user_id, country, region) VALUES (89, 'Sweden', 'Västmanland');
INSERT INTO public.users (user_id, country, region) VALUES (90, 'USA', 'Georgia');
INSERT INTO public.users (user_id, country, region) VALUES (91, 'USA', 'North Carolina');
INSERT INTO public.users (user_id, country, region) VALUES (92, 'Canada', 'Saskatchewan');
INSERT INTO public.users (user_id, country, region) VALUES (93, 'UK', 'East Midlands');
INSERT INTO public.users (user_id, country, region) VALUES (94, 'Germany', 'Baden-Württemberg');
INSERT INTO public.users (user_id, country, region) VALUES (95, 'France', 'Occitanie');
INSERT INTO public.users (user_id, country, region) VALUES (96, 'India', 'Kerala');
INSERT INTO public.users (user_id, country, region) VALUES (97, 'Australia', 'Western Australia');
INSERT INTO public.users (user_id, country, region) VALUES (98, 'Brazil', 'Rio Grande do Sul');
INSERT INTO public.users (user_id, country, region) VALUES (99, 'Japan', 'Fukuoka');
INSERT INTO public.users (user_id, country, region) VALUES (100, 'Mexico', 'Jalisco');
